on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to cr.skpd.io (Private Container Registry)
        uses: docker/login-action@v1 
        with:
          registry: cr.skpd.io
          username: ${{ secrets.SKPD_CR_USERNAME }}
          password: ${{ secrets.SKPD_CR_TOKEN }}
      -
        name: Build and push - Producer
        uses: docker/build-push-action@v2
        with:
          context: ./producer
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iamsavinaykumar/multi-service-celery_producer:latest
            iamsavinaykumar/multi-service-celery_producer:${{ github.sha }}
            cr.skpd.io/multi-service-celery/producer:latest
            cr.skpd.io/multi-service-celery/producer:${{ github.sha}}
      -
        name: Build and push - Monitor
        uses: docker/build-push-action@v2
        with:
          context: ./monitor
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iamsavinaykumar/multi-service-celery_monitor:latest
            iamsavinaykumar/multi-service-celery_monitor:${{ github.sha }}
            cr.skpd.io/multi-service-celery/monitor:latest
            cr.skpd.io/multi-service-celery/monitor:${{ github.sha}}
      -
        name: Build and push - Worker 1
        uses: docker/build-push-action@v2
        with:
          context: ./worker1
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iamsavinaykumar/multi-service-celery_worker1:latest
            iamsavinaykumar/multi-service-celery_worker1:${{ github.sha }}
            cr.skpd.io/multi-service-celery/worker1:latest
            cr.skpd.io/multi-service-celery/worker1:${{ github.sha}}
      -
        name: Build and push - Worker 2
        uses: docker/build-push-action@v2
        with:
          context: ./worker2
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iamsavinaykumar/multi-service-celery_worker2:latest
            iamsavinaykumar/multi-service-celery_worker2:${{ github.sha }}
            cr.skpd.io/multi-service-celery/worker2:latest
            cr.skpd.io/multi-service-celery/worker2:${{ github.sha}}

      -
        name: Build and push - Worker 3
        uses: docker/build-push-action@v2
        with:
          context: ./worker3
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iamsavinaykumar/multi-service-celery_worker3:latest
            iamsavinaykumar/multi-service-celery_worker3:${{ github.sha }}
            cr.skpd.io/multi-service-celery/worker3:latest
            cr.skpd.io/multi-service-celery/worker3:${{ github.sha}}