on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  docker-build-push-producer:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to cr.skpd.io (Private Container Registry)
        uses: docker/login-action@v1 
        with:
          registry: cr.skpd.io
          username: ${{ secrets.SKPD_CR_USERNAME }}
          password: ${{ secrets.SKPD_CR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./producer
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iamsavinaykumar/multi-service-celery_producer:latest
            iamsavinaykumar/multi-service-celery_producer:${{ env.GITHUB_JOB }}
            iamsavinaykumar/multi-service-celery_producer:${{ env.GITHUB_RUN_NUMBER }}
            cr.skpd.io/multi-service-celery/producer:latest
            cr.skpd.io/multi-service-celery/producer:${{ env.GITHUB_JOB }}
            cr.skpd.io/multi-service-celery/producer:${{ env.GITHUB_RUN_NUMBER }}
  docker-build-push-monitor:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to cr.skpd.io (Private Container Registry)
        uses: docker/login-action@v1 
        with:
          registry: cr.skpd.io
          username: ${{ secrets.SKPD_CR_USERNAME }}
          password: ${{ secrets.SKPD_CR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./monitor
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iamsavinaykumar/multi-service-celery_monitor:latest
            iamsavinaykumar/multi-service-celery_monitor:${{ env.GITHUB_JOB }}
            iamsavinaykumar/multi-service-celery_monitor:${{ env.GITHUB_RUN_NUMBER }}
            cr.skpd.io/multi-service-celery/monitor:latest
            cr.skpd.io/multi-service-celery/monitor:${{ env.GITHUB_JOB }}
            cr.skpd.io/multi-service-celery/monitor:${{ env.GITHUB_RUN_NUMBER }}
  docker-build-push-worker1:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to cr.skpd.io (Private Container Registry)
        uses: docker/login-action@v1 
        with:
          registry: cr.skpd.io
          username: ${{ secrets.SKPD_CR_USERNAME }}
          password: ${{ secrets.SKPD_CR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./worker1
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iamsavinaykumar/multi-service-celery_worker1:latest
            iamsavinaykumar/multi-service-celery_worker1:${{ env.GITHUB_JOB }}
            iamsavinaykumar/multi-service-celery_worker1:${{ env.GITHUB_RUN_NUMBER }}
            cr.skpd.io/multi-service-celery/worker1:latest
            cr.skpd.io/multi-service-celery/worker1:${{ env.GITHUB_JOB }}
            cr.skpd.io/multi-service-celery/worker1:${{ env.GITHUB_RUN_NUMBER }}
  docker-build-push-worker2:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to cr.skpd.io (Private Container Registry)
        uses: docker/login-action@v1 
        with:
          registry: cr.skpd.io
          username: ${{ secrets.SKPD_CR_USERNAME }}
          password: ${{ secrets.SKPD_CR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./worker2
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iamsavinaykumar/multi-service-celery_worker2:latest
            iamsavinaykumar/multi-service-celery_worker2:${{ env.GITHUB_JOB }}
            iamsavinaykumar/multi-service-celery_worker2:${{ env.GITHUB_RUN_NUMBER }}
            cr.skpd.io/multi-service-celery/worker2:latest
            cr.skpd.io/multi-service-celery/worker2:${{ env.GITHUB_JOB }}
            cr.skpd.io/multi-service-celery/worker2:${{ env.GITHUB_RUN_NUMBER }}
  docker-build-push-worker3:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to cr.skpd.io (Private Container Registry)
        uses: docker/login-action@v1 
        with:
          registry: cr.skpd.io
          username: ${{ secrets.SKPD_CR_USERNAME }}
          password: ${{ secrets.SKPD_CR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./worker3
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iamsavinaykumar/multi-service-celery_worker3:latest
            iamsavinaykumar/multi-service-celery_worker3:${{ env.GITHUB_JOB }}
            iamsavinaykumar/multi-service-celery_worker3:${{ env.GITHUB_RUN_NUMBER }}
            cr.skpd.io/multi-service-celery/worker3:latest
            cr.skpd.io/multi-service-celery/worker3:${{ env.GITHUB_JOB }}
            cr.skpd.io/multi-service-celery/worker3:${{ env.GITHUB_RUN_NUMBER }}
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      -
        name: Build and push - Monitor
        uses: docker/build-push-action@v2
        with:
          context: ./monitor
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iamsavinaykumar/multi-service-celery_monitor:latest
            iamsavinaykumar/multi-service-celery_monitor:$GITHUB_JOB
            iamsavinaykumar/multi-service-celery_monitor:$GITHUB_RUN_NUMBER
            cr.skpd.io/multi-service-celery/monitor:latest
            cr.skpd.io/multi-service-celery/monitor:$GITHUB_JOB
            cr.skpd.io/multi-service-celery/monitor:$GITHUB_RUN_NUMBER
      -
        name: Build and push - Worker 1
        uses: docker/build-push-action@v2
        with:
          context: ./worker1
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iamsavinaykumar/multi-service-celery_worker1:latest
            iamsavinaykumar/multi-service-celery_worker1:$GITHUB_JOB
            iamsavinaykumar/multi-service-celery_worker1:$GITHUB_RUN_NUMBER
            cr.skpd.io/multi-service-celery/worker1:latest
            cr.skpd.io/multi-service-celery/worker1:$GITHUB_JOB
            cr.skpd.io/multi-service-celery/worker1:$GITHUB_RUN_NUMBER
      -
        name: Build and push - Worker 2
        uses: docker/build-push-action@v2
        with:
          context: ./worker2
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iamsavinaykumar/multi-service-celery_worker2:latest
            iamsavinaykumar/multi-service-celery_worker2:$GITHUB_JOB
            iamsavinaykumar/multi-service-celery_worker2:$$GITHUB_RUN_NUMBER
            cr.skpd.io/multi-service-celery/worker2:latest
            cr.skpd.io/multi-service-celery/worker2:$GITHUB_JOB
            cr.skpd.io/multi-service-celery/worker2:$$GITHUB_RUN_NUMBER

      -
        name: Build and push - Worker 3
        uses: docker/build-push-action@v2
        with:
          context: ./worker3
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iamsavinaykumar/multi-service-celery_worker3:latest
            iamsavinaykumar/multi-service-celery_worker3:$GITHUB_JOB
            iamsavinaykumar/multi-service-celery_worker3:$$GITHUB_RUN_NUMBER
            cr.skpd.io/multi-service-celery/worker3:latest
            cr.skpd.io/multi-service-celery/worker3:$GITHUB_JOB
            cr.skpd.io/multi-service-celery/worker3:$$GITHUB_RUN_NUMBER