on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push - Producer
        uses: docker/build-push-action@v2
        with:
          context: ./producer
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iamsavinaykumar/multi-service-celery_producer:latest
            iamsavinaykumar/multi-service-celery_producer:${{ GITHUB_SHA }}
      -
        name: Build and push - Worker 1
        uses: docker/build-push-action@v2
        with:
          context: ./worker1
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iamsavinaykumar/multi-service-celery_worker1:latest
            iamsavinaykumar/multi-service-celery_worker1:${{ GITHUB_SHA }}
      -
        name: Build and push - Worker 2
        uses: docker/build-push-action@v2
        with:
          context: ./worker2
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iamsavinaykumar/multi-service-celery_worker2:latest
            iamsavinaykumar/multi-service-celery_worker2:${{ GITHUB_SHA }}
      -
        name: Build and push - Worker 3
        uses: docker/build-push-action@v2
        with:
          context: ./worker3
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iamsavinaykumar/multi-service-celery_worker3:latest
            iamsavinaykumar/multi-service-celery_worker3:${{ GITHUB_SHA }}